<?php
$field_vehicle[7][5] = 7;
$field_vehicle[20][6] = 6;
$field_vehicle[18][10] = 1;
$field_vehicle[0][60] = 11;

$field_vechicle[50][50] = 50;

$vehicle_data[7]["set"] = 5;
$vehicle_data[6]["set"] = 15;
$vehicle_data[1]["set"] = 3;
$vehicle_data[11]["set"] = 7;
$vehicle_data[50]["set"] = 10;



$field_blocked[9][6] = 1;
$field_blocked[9][7] = 1;
$field_blocked[9][8] = 1;

$field_blocked[10][5] = 1;
$field_blocked[10][6] = 1;
$field_blocked[10][7] = 1;
$field_blocked[10][8] = 1;

$field_blocked[11][7] = 1;
$field_blocked[11][8] = 1;
$field_blocked[11][9] = 1;

$field_blocked[9][6] = 1;
$field_blocked[9][7] = 1;
$field_blocked[9][8] = 1;

$field_blocked[14][5] = 1;
$field_blocked[15][6] = 1;
$field_blocked[16][7] = 1;
$field_blocked[17][8] = 1;

$field_blocked[21][7] = 1;
$field_blocked[21][8] = 1;
$field_blocked[21][9] = 1;

$field_blocked[69][5] = 1;
$field_blocked[69][6] = 1;
$field_blocked[80][7] = 1;
$field_blocked[80][8] = 1;

$field_blocked[71][7] = 1;
$field_blocked[71][8] = 1;
$field_blocked[71][9] = 1;

?>